import { TOOLS_LEGACY } from './catalog';
import * as renderers from './renderers';

export const LEGACY_RENDERERS = {
  'renderUnifiedCounter': renderUnifiedCounter,
  'renderWordCloud': renderWordCloud,
  'renderCaseConverter': renderCaseConverter,
  'renderEncoderDecoder': renderEncoderDecoder,
  'renderPasswordGen': renderPasswordGen,
  'renderFindReplace': renderFindReplace,
  'renderFrequency': renderFrequency,
  'renderDuplicateWords': renderDuplicateWords,
  'renderCountOccurrences': renderCountOccurrences,
  'renderAddPrefix': renderAddPrefix,
  'renderFilterLines': renderFilterLines,
  'renderLineNumbers': renderLineNumbers,
  'renderWrapText': renderWrapText,
  'renderMarkdownStripper': renderMarkdownStripper,
  'renderHtmlStripper': renderHtmlStripper,
  'renderInvisibleChars': renderInvisibleChars,
  'renderDelimiterConverter': renderDelimiterConverter,
  'renderUuidGenerator': renderUuidGenerator,
  'renderHexConverter': renderHexConverter,
  'renderMorseBinary': renderMorseBinary,
  'renderTextToImage': renderTextToImage,
  'renderLoremIpsum': renderLoremIpsum,
  'renderJsonStringify': renderJsonStringify,
  'renderCaesarCipher': renderCaesarCipher,
  'renderVigenereCipher': renderVigenereCipher,
  'renderPigpenCipher': renderPigpenCipher,
  'renderPlatformCounter': renderPlatformCounter,
  'renderReadabilityAnalyzer': renderReadabilityAnalyzer,
  'renderQRCodeGenerator': renderQRCodeGenerator,
  'renderLeetspeakConverter': renderLeetspeakConverter,
  'renderTextToEmoji': renderTextToEmoji,
  'renderAsciiArt': renderAsciiArt,
  'renderAcrosticGenerator': renderAcrosticGenerator,
  'renderFakeChatGenerator': renderFakeChatGenerator,
  'renderTabsSpaces': renderTabsSpaces,
  'renderSmartQuotes': renderSmartQuotes,
  'renderSplitJoin': renderSplitJoin,
  'renderCompareText': renderCompareText,
  'renderCsvConverter': renderCsvConverter,
  'renderTextToSpeech': renderTextToSpeech,
  'renderRandomString': renderRandomString,
  'renderRegexTester': renderRegexTester,
  'renderCensorWords': renderCensorWords,
  'renderReverseAdvanced': renderReverseAdvanced,
  'renderSortAdvanced': renderSortAdvanced,
  'renderDuplicateRemoverWords': renderDuplicateRemoverWords,
  'renderPadText': renderPadText,
  'renderHashGenerator': renderHashGenerator,
  'renderUnicodeInfo': renderUnicodeInfo,
  'renderPalindromeCheck': renderPalindromeCheck,
  'renderZalgoText': renderZalgoText,
  'renderFancyText': renderFancyText,
  'renderTextRepeater': renderTextRepeater,
  'renderHighlightPatterns': renderHighlightPatterns,
  'renderTextEntropy': renderTextEntropy,
  'renderLevenshtein': renderLevenshtein,
  'renderNumberToWords': renderNumberToWords,
  'renderBraille': renderBraille,
  'renderJsonFormatter': renderJsonFormatter,
  'renderHtmlEntities': renderHtmlEntities,
  'renderMarkdownPreview': renderMarkdownPreview,
  'renderPatternExtractor': renderPatternExtractor,
  'renderDiff': renderDiff,
  'renderChecksum': renderChecksum,
  'renderUrlParser': renderUrlParser,
  'renderJwtDecoder': renderJwtDecoder,
  'renderCodePoints': renderCodePoints,
  'renderDateTimeConverter': renderDateTimeConverter,
  'renderColorConverter': renderColorConverter,
  'renderTableConverter': renderTableConverter,
  'renderPlayfair': renderPlayfair
};

export { TOOLS_LEGACY, renderers };
