import type { CompactTags } from '@/types';

export const COMPACT_TAGS: CompactTags = {
  'duplicate-words-in-text': [
    'podvoji besede',
    'ponovi vsako besedo',
    'duplicate words',
    'podvajanje besed',
    'duplicate each word',
    'ponavljaj besede',
    'text doubler',
    'word doubler',
  ],
  'replace-spaces-in-text': [
    'zamenjaj presledke',
    'presledki v črtice',
    'replace spaces',
    'space to dash',
    'space to underscore',
    'presledek v crtico',
    'presledek v podcrtaj',
    'url slugify spaces',
    'slug spaces',
    'remove spaces',
  ],
  'replace-line-breaks-in-text': [
    'zamenjaj prelome',
    'prelomi v vejice',
    'replace line breaks',
    'newline to comma',
    'newline to space',
    'prelom v vejico',
    'prelom v presledek',
    'join lines',
    'združi vrstice',
    'flatten text',
    'single line',
  ],
  'remove-emojis': [
    'brez emojijev',
    'odstrani emotikone',
    'remove emojis',
    'strip emojis',
    'clean emoji',
    'odstrani emoji',
    'emoji remover',
    'text cleaner',
    'remove symbols',
  ],
  'remove-line-numbers': [
    'odstrani oštevilčenje',
    'alineje',
    'bullet points',
    'poišči seznam',
    'remove numbering',
    'strip numbers',
    'remove bullets',
    'clean list',
    'odstrani stevilke',
    'odstrani alineje',
    'numbered list cleaner',
  ],
  'add-quotes-to-lines': [
    'narekovaji vrsticam',
    'dodaj narekovaje',
    'quote lines',
    'wrap lines in quotes',
    'add quotes',
    'enclose lines',
    'csv quote lines',
    'json quote lines',
    'narekovaji na vrstice',
    'navadni narekovaji',
    'enojni narekovaji',
  ],
  'spaces-to-newlines': [
    'presledki v vrstice',
    'vsaka beseda v vrstico',
    'space to newline',
    'split by space',
    'word per line',
    'beseda na vrstico',
    'razdeli po presledkih',
    'text to column',
    'vertical text',
  ],
  'newlines-to-spaces': [
    'vrstice v presledke',
    'združi v eno vrstico',
    'newline to space',
    'join lines',
    'flatten lines',
    'single line text',
    'prelomi v presledke',
    'merge lines',
    'concatenate lines',
  ],
  'comma-to-newline': [
    'vejice v vrstice',
    'razdeli po vejicah',
    'seznam iz vejic',
    'comma to newline',
    'split by comma',
    'csv to list',
    'vejica v novovrstico',
    'razdeli csv',
    'comma separated to lines',
  ],
  'newline-to-comma': [
    'vrstice v vejice',
    'seznam z vejicami',
    'newline to comma',
    'join with comma',
    'lines to csv',
    'list to csv',
    'prelomi v vejice',
    'vrstice v csv',
    'merge with comma',
  ],
};
